### ISSUE TITLE
Loging

### ISSUE THREAD

**Issue by wj-turner** [wj-turner/OmegaFin#19]
For centralized logging in a development environment (especially with multiple services like in your application), using a logging stack like the ELK (Elasticsearch, Logstash, Kibana) or EFK (Elasticsearch, Fluentd, Kibana) can be very beneficial.

Here's a brief overview:

1. **Elasticsearch:** It's a search and analytics engine. Logs from various services are stored and indexed here.
2. **Logstash/Fluentd:** These are server-side data processing pipelines that ingest data from multiple sources simultaneously, transform it, and then send it to a stash like Elasticsearch.
3. **Kibana:** A visualization tool that works on top of Elasticsearch. It provides a web interface where you can visualize and analyze the logs.

Given your setup, here's how you can integrate an ELK stack into your Docker environment:

1. **Add Services to Docker Compose**

In your `docker-compose.yml`, add the following:

```yaml
services:
  ...
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - backend

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.0
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    depends_on:
      - elasticsearch
    networks:
      - backend

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - backend

volumes:
  ...
  es-data:
```

2. **Logstash Configuration**

In the directory structure, under the `docker` directory, you'd need to add a sub-directory for `logstash` that contains its configuration. Here's an example of what the directory and files might look like:

```
docker/
├── logstash/
│   ├── config/
│   │   └── logstash.yml
│   └── pipeline/
│       └── logstash.conf
```

- `logstash.yml` is the main configuration file.
  
- `logstash.conf` defines how to process and send logs to Elasticsearch. This can be set up to collect logs from your services (e.g., via filebeat or directly from a directory).

3. **Gathering Logs**

For gathering logs, you have multiple options:

- **Directly from a directory:** Your applications could be configured to log to a volume that Logstash then reads.
  
- **Using Filebeat:** This is a lightweight log shipper that can send logs to Logstash. This can be added as another service in your `docker-compose` if necessary.

4. **Visualize in Kibana**

Once everything is running, you can access Kibana at `http://localhost:5601`. From here, you can set up dashboards, search logs, and more.

Remember, while this setup is great for a development environment, in production, you might need to consider scalability, security (like securing Elasticsearch and Kibana), and more advanced configurations.
