### ISSUE TITLE
Monitoring

### ISSUE THREAD

**Issue by wj-turner** [wj-turner/OmegaFin#6]
For monitoring a containerized application, especially in a development environment, you have several great options. I'll suggest Prometheus in combination with Grafana, as they are popular, robust, and well-integrated solutions for monitoring and visualization.

1. **Prometheus:** It's an open-source monitoring solution that can scrape metrics from different sources. In a Docker environment, the combination of Prometheus with cAdvisor and node-exporter is common:

   - **cAdvisor (Container Advisor)**: Provides container users with an understanding of the resource usage and performance characteristics of their running containers.
   
   - **node-exporter**: Exposes a wide variety of hardware and OS metrics.

2. **Grafana:** A platform for monitoring and observability. It lets you query, visualize, alert on, and understand your metrics no matter where they are stored.

Here's a basic integration guide:

### Docker Compose Configuration

In your `docker-compose.yml`, you can add the following:

```yaml
services:
  ...

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    depends_on:
      - cadvisor

  cadvisor:
    image: google/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080

  node-exporter:
    image: prom/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    depends_on:
      - prometheus

```

### Prometheus Configuration

You'll need a `prometheus.yml` config in your project directory. Here's a basic example:

```yaml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']

```

### Monitoring Your Services

If your services (like FastAPI) expose Prometheus metrics (usually at `/metrics` endpoint), you can add them to the `prometheus.yml` under `scrape_configs`.

### Visualization with Grafana

Once everything is running:

1. Open Grafana at `http://localhost:3000`.
2. Login with `admin`/`admin` (default credentials).
3. Add Prometheus as a data source.
4. Start creating dashboards or import existing ones to visualize your metrics.

### Conclusion

This basic setup gives you a robust monitoring solution for a development environment. For production, considerations for secure access, data retention, alerts, and scalability should be made.
